[package]
name = "rust"
version = "0.1.0"
authors = ["Mikail Khan <mikail.khan45@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6"

[dependencies.sdl2]
version = "0.32.2"
default-features = false
features = ["gfx"]
